export EDITOR=/usr/bin/vim
export VISUAL=/usr/bin/vim
alias l='ls --color=auto -ACFrt'
alias ll='ls --color=auto -AFlrt'

if ! [[ "$PATH" =~ "$HOME/.local/bin" ]]
then
  export PATH="$HOME/.local/bin:$PATH"

fi
